### ISSUE TITLE
Enable Stackblitz Demos

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux2-docs#457]
#414 created the foundation for interfacing with Stackblitz, as well as enabling any demo that successfully worked.  The following are demos that need to be addressed before enabling:

"Error in src/styles.scss Error: ENOENT: No such file or directory., '/dev/null'";
  - code-block
  - copy-button

No component factory found for SkySummaryActionBarModalDemoComponent. Did you add it to @NgModule.entryComponents?:
  - summary-actionbar

i18n keys are shown instead of values
  - numeric

SkyLibResourcesService injector error
  - text-expand
  - text-expand-repeater
  - tokens

NullInjectorError: No provider for SkyLogService!
  - sort

StaticInjectorError(Platform: core)[SkyPopoverComponent -> SkyWindowRefService]
  - progress-indicator

Grid view requires at least one sky-grid-column to render.
  - list
  - list-filters
  - list-paging
  - list-toolbar
  - list-grid

Can not read property getWindow of null
  - wizard

Unknown error (need to dig in more)
  - infinite-scroll

No error, but not grid not rendering:
  - flyout
  - list-checklist
  - select-field

**Comment by blackbaud-johnly** [comment]
- The wizard component also doesn’t have a StackBlitz button. Should it? I assume not because it’s essentially a deprecated component, but I want to make sure.
- Unlike the other components listed here, progress indicator has a StackBlitz button. Should it? When you click the button, the StackBlitz demo only loads the demo headers and none of the other demo content.
- The grid and sectioned form components also have StackBlitz buttons and only load demo headers and not the rest of the content.
- The filter, paging, repeater, and search demos don’t work in StackBlitz. They can’t find the package @skyux/list-builder.
- The tile and vertical tabs demos don’t seem to work in StackBlitz. They just load blank screens.

**Comment by blackbaud-johnly** [comment]
Also, the StackBlitz button is not working for date range picker.

**Comment by blackbaud-johnly** [comment]
The StackBlitz demo for the phone field component indicates that it is missing the @skyux/lookup package. But when you install it, an error occurs:

Error in /turbo_modules/@angular/compiler@8.2.7/bundles/compiler.umd.js (2603:21)
Unexpected value 'undefined' exported by the module 'AppSkyModule'

I'm going to hide the StackBlitz button for this component, along with the other buttons where I found issues.

**Comment by isaacaggrey** [comment]
Is this the tracking issue for components missing Stackblitz? Is this someone can contribute?

I'm trying to reproduce an issue for the sky-phone-field and it has no Stackblitz that I can demonstrate the issue.

**Comment by blackbaud-johnly** [comment]
@isaacaggrey, you are right that this issue is for tracking the components where Stackblitz demos are missing. But I don't know that it'd be worth the effort to contribute a Stackblitz demo at this time. We are updating the design patterns of our component documentation, and as we migrate existing docs to the new patterns, we are converting the demos. As we convert the components in this issue, we will address the missing Stackblitz demos. Sorry that the phone field demo isn't currently in place for you now.

**Comment by Blackbaud-MichaelCollier** [comment]
Re-design component docs will address this issue.  This will be over time and not immediate but this will be resolved as the individual docs are updated.

**Comment by Blackbaud-IsaacAggrey** [comment]
@Blackbaud-MichaelCollier are there tracking issues for each component that have been created? Or are those things not open for outside contribution?

**Comment by blackbaud-johnly** [comment]
@isaacaggrey, we don't have individual issues. We'll address the Stackblitz issue when we create demos and convert existing docs to the new pattern. There are a lot of moving pieces, but that just means contributions would require looping the developer into our docs conversion process. If you want more info on that, please reach out to me on Slack . Thanks!
