### ISSUE TITLE
Update name property description for skyuxconfig.json

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#916]
Based on internal questions on Slack, it seems like our docs at https://developer.blackbaud.com/skyux/learn/reference/configuration#name are misleading for internal developers and like the description needs to be updated to more accurately reflect different behavior for internal vs external developers.

Talked to @Blackbaud-TerryHelems about this one, and we probably need @Blackbaud-BobbyEarl's input here.

**Comment by Blackbaud-BobbyEarl** [comment]
There's so much there to rework.

I think the most important thing is to remove anything that talks about host since A) that's Blackbaud-specific and B) changing that value will appear to work while serving but won't work in production since that value is stamped in the pipeline when it's created.

We may be able to simply reduce it to the following hierarchy in regards to the base url the SPA wants to be rendered at.

- `app.base` in `skyuxconfig.json`
- `name` in `skyuxconfig.json`
- `name` in `package.json`

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/924.
